using System.Reflection;
using System.Text.Json;
using Core.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using StackExchange.Redis;

namespace Infrastructure.Data.DataSeed;

public class DataSeed
{
    public async static Task SeedingData(StoreDbContext storeDbContext, UserManager<ApplicationUser> userManager)
    {
        var path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

        var hasProduct = await storeDbContext.Products.AnyAsync();
        var hasDelivery = await storeDbContext.DeliveryMethods.AnyAsync();
        var hasUsers = await storeDbContext.Users.AnyAsync();
        if (hasDelivery && hasProduct && hasUsers)
            return;

        if (!hasProduct)
        {
            var data = await File.ReadAllTextAsync(path + @"/Data/DataSeed/products.json");
            if (string.IsNullOrEmpty(data))
                return;
            var products = JsonSerializer.Deserialize<List<Product>>(data);

            await storeDbContext.Products.AddRangeAsync(products!);
        }
        if (!hasDelivery)
        {
            var data = await File.ReadAllTextAsync(path + @"/Data/DataSeed/delivery.json");
            if (string.IsNullOrEmpty(data))
                return;
            var deliveries = JsonSerializer.Deserialize<List<DeliveryMethod>>(data);

            await storeDbContext.DeliveryMethods.AddRangeAsync(deliveries!);
        }

        if (!hasUsers)
        {
            var data = await File.ReadAllTextAsync(path + @"/Data/DataSeed/users.json");
            if (string.IsNullOrEmpty(data))
                return;

            var users = JsonSerializer.Deserialize<List<ApplicationUser>>(data);
            if (users == null || !users.Any())
                return;

            // 1. Seed the Users safely
            await storeDbContext.Users.AddRangeAsync(users);

            // 2. Seed the Roles if they don't exist yet
            if (!await storeDbContext.Roles.AnyAsync())
            {
                await storeDbContext.Roles.AddRangeAsync([
                    new IdentityRole { Id = "2c5e174e-3b2e-445e-a010-85f0ef32d3f4", Name = "Admin", NormalizedName = "ADMIN" },
                    new IdentityRole { Id = "5a4f318b-8211-4cb3-91de-12bf134b77aa", Name = "Member", NormalizedName = "MEMBER" }
                ]);
            }

            // Save to make sure IDs are trackable/present if generated by database (though we have them hardcoded in JSON)
            await storeDbContext.SaveChangesAsync();

            // 3. Find the target users from our deserialized collection using the emails from your JSON structure
            var adminUser = users.FirstOrDefault(e => e.Email == "admin@test.com");
            var memberUser = users.FirstOrDefault(e => e.Email == "tom@test.com");

            if (adminUser is not null && memberUser is not null)
            {
                // 4. Map user IDs directly to role IDs via UserRoles DbSet
                await storeDbContext.UserRoles.AddRangeAsync([
                    new IdentityUserRole<string>
            {
                UserId = adminUser.Id,
                RoleId = "2c5e174e-3b2e-445e-a010-85f0ef32d3f4" // Matches Admin Role Id
            },
            new IdentityUserRole<string>
            {
                UserId = memberUser.Id,
                RoleId = "5a4f318b-8211-4cb3-91de-12bf134b77aa" // Matches Member Role Id
            }
                ]);

                await storeDbContext.SaveChangesAsync();
            }
        }

        await storeDbContext.SaveChangesAsync();


    }

}
